import { environment } from '../environments/environment';
import currencies from '../assets/data/currencies.json'

export interface Currency {
  symbol: string,
  name: string,
  "symbol_native": string,
  "decimal_digits": number,
  "code": string,
}

export interface Country {
  name: string,
  code: string,
  flag: string,
  placeholder: string,
  dialCode: string,
}

export const DEFAULT_TOAST_DURATION = 2000;
export const PRIVATE_API = `${environment.apiBaseUrl}/api/v1`;
export const PUBLIC_API = environment.apiBaseUrl;
export const CURRENCIES: Currency[] = currencies;
export const CURRENCIES_CODES: string[] = currencies.map(currency => currency.code);
export const PHONE_MASKS: { [key: string]: any } = {
  'AF': {
    mask: [
      '0', /\d/, /\d/, ' ', /\d/, /\d/, /\d/, ' ', /\d/, /\d/, /\d/, /\d/,
    ],
    autocomplete: 'tel',
    overwriteMode: 'shift',
  },
  'AU': {
    mask: [
      '0', '4', /\d/, /\d/, ' ', /\d/, /\d/, /\d/, ' ', /\d/, /\d/, /\d/,
    ],
    autocomplete: 'tel',
    overwriteMode: 'shift',
  },
  'DE': {
    mask: [
      '+', '4', '9', ' ', '1', /\d/, /\d/, ' ', /\d/, /\d/, /\d/, ' ', /\d/, /\d/, /\d/, /\d/
    ],
    autocomplete: 'tel',
    overwriteMode: 'shift',
  },
  'PK': {
    mask: [
      '0', '3', /\d/, /\d/, ' ', /\d/, /\d/, /\d/, /\d/, /\d/, /\d/, /\d/,
    ],
    autocomplete: 'tel',
    overwriteMode: 'shift',
  },
  'IN': {
    mask: [
      /[9|8|7]/, /\d/, /\d/, /\d/, /\d/, ' ', /\d/, /\d/, /\d/, /\d/, /\d/,
    ],
    autocomplete: 'tel',
    overwriteMode: 'shift',
  },
  'US': {
    mask: [
      '(', /\d/, /\d/, /\d/, ')', ' ', /\d/, /\d/, /\d/, '-', /\d/, /\d/, /\d/, /\d/,
    ],
    autocomplete: 'tel',
    overwriteMode: 'shift',
  },
  'GB': {
    mask: [
      '0', '7', /\d/, /\d/, /\d/, ' ', /\d/, /\d/, /\d/, /\d/, /\d/, /\d/,
    ],
    autocomplete: 'tel',
    overwriteMode: 'shift',
  },
  'TH': {
    mask: [
      '0', '8', /\d/, ' ', /\d/, /\d/, /\d/, ' ', /\d/, /\d/, /\d/, /\d/,
    ],
    autocomplete: 'tel',
    overwriteMode: 'shift',
  },
  'SG': {
    mask: [
      '9', /\d/, /\d/, /\d/, ' ', /\d/, /\d/, /\d/, /\d/,
    ],
    autocomplete: 'tel',
    overwriteMode: 'shift',
  },
  'CN': {
    mask: [
      '1', /\d/, /\d/, ' ', /\d/, /\d/, /\d/, /\d/, ' ', /\d/, /\d/, /\d/, /\d/,
    ],
    autocomplete: 'tel',
    overwriteMode: 'shift',
  },
};
export const COUNTRIES_WITH_CALLING_CODES: Country[] = [
  {
    "name": "Afghanistan",
    "code": "AF",
    "flag": "🇦🇫",
    "placeholder": "0xx yyy-yyyy",
    "dialCode": "+93",
  },
  {
    "name": "Albania",
    "code": "AL",
    "flag": "🇦🇱",
    "placeholder": "",
    "dialCode": "+355",
  },
  {
    "name": "Andorra",
    "code": "AD",
    "flag": "🇦🇩",
    "placeholder": "",
    "dialCode": "+376",
  },
  {
    "name": "Angola",
    "code": "AO",
    "flag": "🇦🇴",
    "placeholder": "",
    "dialCode": "+244",
  },
  {
    "name": "Anguilla",
    "code": "AI",
    "flag": "🇦🇮",
    "placeholder": "",
    "dialCode": "+1264",
  },
  {
    "name": "Antarctica",
    "code": "AQ",
    "flag": "🇦🇶",
    "placeholder": "",
    "dialCode": "+672",
  },
  {
    "name": "Antigua & Barbuda",
    "code": "AG",
    "flag": "🇦🇬",
    "placeholder": "",
    "dialCode": "+1268",
  },
  {
    "name": "Argentina",
    "code": "AR",
    "flag": "🇦🇷",
    "placeholder": "",
    "dialCode": "+54",
  },
  {
    "name": "Armenia",
    "code": "AM",
    "flag": "🇦🇲",
    "placeholder": "",
    "dialCode": "+374",
  },
  {
    "name": "Aruba",
    "code": "AW",
    "flag": "🇦🇼",
    "placeholder": "",
    "dialCode": "+297",
  },
  {
    "name": "Ascension Island",
    "code": "AC",
    "flag": "🇦🇨",
    "placeholder": "",
    "dialCode": "+",
  },
  {
    "name": "Australia",
    "code": "AU",
    "flag": "🇦🇺",
    "placeholder": "",
    "dialCode": "+61",
  },
  {
    "name": "Austria",
    "code": "AT",
    "flag": "🇦🇹",
    "placeholder": "",
    "dialCode": "+43",
  },
  {
    "name": "Azerbaijan",
    "code": "AZ",
    "flag": "🇦🇿",
    "placeholder": "",
    "dialCode": "+994",
  },
  {
    "name": "Bahamas",
    "code": "BS",
    "flag": "🇧🇸",
    "placeholder": "",
    "dialCode": "+1242",
  },
  {
    "name": "Bahrain",
    "code": "BH",
    "flag": "🇧🇭",
    "placeholder": "",
    "dialCode": "+973",
  },
  {
    "name": "Bangladesh",
    "code": "BD",
    "flag": "🇧🇩",
    "placeholder": "",
    "dialCode": "+880",
  },
  {
    "name": "Barbados",
    "code": "BB",
    "flag": "🇧🇧",
    "placeholder": "",
    "dialCode": "+1246",
  },
  {
    "name": "Belarus",
    "code": "BY",
    "flag": "🇧🇾",
    "placeholder": "",
    "dialCode": "+375",
  },
  {
    "name": "Belgium",
    "code": "BE",
    "flag": "🇧🇪",
    "placeholder": "",
    "dialCode": "+32",
  },
  {
    "name": "Belize",
    "code": "BZ",
    "flag": "🇧🇿",
    "placeholder": "",
    "dialCode": "+501",
  },
  {
    "name": "Benin",
    "code": "BJ",
    "flag": "🇧🇯",
    "placeholder": "",
    "dialCode": "+229",
  },
  {
    "name": "Bermuda",
    "code": "BM",
    "flag": "🇧🇲",
    "placeholder": "",
    "dialCode": "+1441",
  },
  {
    "name": "Bhutan",
    "code": "BT",
    "flag": "🇧🇹",
    "placeholder": "",
    "dialCode": "+975",
  },
  {
    "name": "Bolivia",
    "code": "BO",
    "flag": "🇧🇴",
    "placeholder": "",
    "dialCode": "+591",
  },
  {
    "name": "Bosnia & Herzegovina",
    "code": "BA",
    "flag": "🇧🇦",
    "placeholder": "",
    "dialCode": "+387",
  },
  {
    "name": "Botswana",
    "code": "BW",
    "flag": "🇧🇼",
    "placeholder": "",
    "dialCode": "+267",
  },
  {
    "name": "Brazil",
    "code": "BR",
    "flag": "🇧🇷",
    "placeholder": "",
    "dialCode": "+55",
  },
  {
    "name": "Brunei",
    "code": "BN",
    "flag": "🇧🇳",
    "placeholder": "",
    "dialCode": "+673",
  },
  {
    "name": "Bulgaria",
    "code": "BG",
    "flag": "🇧🇬",
    "placeholder": "",
    "dialCode": "+359",
  },
  {
    "name": "Burkina Faso",
    "code": "BF",
    "flag": "🇧🇫",
    "placeholder": "",
    "dialCode": "+226",
  },
  {
    "name": "Burundi",
    "code": "BI",
    "flag": "🇧🇮",
    "placeholder": "",
    "dialCode": "+257",
  },
  {
    "name": "Cabo Verde",
    "code": "CV",
    "flag": "🇨🇻",
    "placeholder": "",
    "dialCode": "+238",
  },
  {
    "name": "Cambodia",
    "code": "KH",
    "flag": "🇰🇭",
    "placeholder": "",
    "dialCode": "+855",
  },
  {
    "name": "Cameroon",
    "code": "CM",
    "flag": "🇨🇲",
    "placeholder": "",
    "dialCode": "+237",
  },
  {
    "name": "Canada",
    "code": "CA",
    "flag": "🇨🇦",
    "placeholder": "",
    "dialCode": "+1",
  },
  {
    "name": "Cayman Islands",
    "code": "KY",
    "flag": "🇰🇾",
    "placeholder": "",
    "dialCode": "+1345",
  },
  {
    "name": "Central African Republic",
    "code": "CF",
    "flag": "🇨🇫",
    "placeholder": "",
    "dialCode": "+236",
  },
  {
    "name": "Chad",
    "code": "TD",
    "flag": "🇹🇩",
    "placeholder": "",
    "dialCode": "+235",
  },
  {
    "name": "Chile",
    "code": "CL",
    "flag": "🇨🇱",
    "placeholder": "",
    "dialCode": "+56",
  },
  {
    "name": "China",
    "code": "CN",
    "flag": "🇨🇳",
    "placeholder": "138 1234 5678",
    "dialCode": "+86",
  },
  {
    "name": "Colombia",
    "code": "CO",
    "flag": "🇨🇴",
    "placeholder": "",
    "dialCode": "+57",
  },
  {
    "name": "Comoros",
    "code": "KM",
    "flag": "🇰🇲",
    "placeholder": "",
    "dialCode": "+269",
  },
  {
    "name": "Congo - Brazzaville",
    "code": "CG",
    "flag": "🇨🇬",
    "placeholder": "",
    "dialCode": "+242",
  },
  {
    "name": "Congo - Kinshasa",
    "code": "CD",
    "flag": "🇨🇩",
    "placeholder": "",
    "dialCode": "+243",
  },
  {
    "name": "Cook Islands",
    "code": "CK",
    "flag": "🇨🇰",
    "placeholder": "",
    "dialCode": "+682",
  },
  {
    "name": "Costa Rica",
    "code": "CR",
    "flag": "🇨🇷",
    "placeholder": "",
    "dialCode": "+506",
  },
  {
    "name": "Croatia",
    "code": "HR",
    "flag": "🇭🇷",
    "placeholder": "",
    "dialCode": "+385",
  },
  {
    "name": "Cuba",
    "code": "CU",
    "flag": "🇨🇺",
    "placeholder": "",
    "dialCode": "+53",
  },
  {
    "name": "Curaçao",
    "code": "CW",
    "flag": "🇨🇼",
    "placeholder": "",
    "dialCode": "+599",
  },
  {
    "name": "Cyprus",
    "code": "CY",
    "flag": "🇨🇾",
    "placeholder": "",
    "dialCode": "+357",
  },
  {
    "name": "Czechia",
    "code": "CZ",
    "flag": "🇨🇿",
    "placeholder": "",
    "dialCode": "+420",
  },
  {
    "name": "Côte d’Ivoire",
    "code": "CI",
    "flag": "🇨🇮",
    "placeholder": "",
    "dialCode": "+225",
  },
  {
    "name": "Denmark",
    "code": "DK",
    "flag": "🇩🇰",
    "placeholder": "",
    "dialCode": "+45",
  },
  {
    "name": "Djibouti",
    "code": "DJ",
    "flag": "🇩🇯",
    "placeholder": "",
    "dialCode": "+253",
  },
  {
    "name": "Dominica",
    "code": "DM",
    "flag": "🇩🇲",
    "placeholder": "",
    "dialCode": "+1767",
  },
  {
    "name": "Dominican Republic",
    "code": "DO",
    "flag": "🇩🇴",
    "placeholder": "",
    "dialCode": "+1 809, +1 829, +1 849",
  },
  {
    "name": "Ecuador",
    "code": "EC",
    "flag": "🇪🇨",
    "placeholder": "",
    "dialCode": "+593",
  },
  {
    "name": "Egypt",
    "code": "EG",
    "flag": "🇪🇬",
    "placeholder": "",
    "dialCode": "+20",
  },
  {
    "name": "El Salvador",
    "code": "SV",
    "flag": "🇸🇻",
    "placeholder": "",
    "dialCode": "+503",
  },
  {
    "name": "Equatorial Guinea",
    "code": "GQ",
    "flag": "🇬🇶",
    "placeholder": "",
    "dialCode": "+240",
  },
  {
    "name": "Eritrea",
    "code": "ER",
    "flag": "🇪🇷",
    "placeholder": "",
    "dialCode": "+291",
  },
  {
    "name": "Estonia",
    "code": "EE",
    "flag": "🇪🇪",
    "placeholder": "",
    "dialCode": "+372",
  },
  {
    "name": "Eswatini",
    "code": "SZ",
    "flag": "🇸🇿",
    "placeholder": "",
    "dialCode": "+268",
  },
  {
    "name": "Ethiopia",
    "code": "ET",
    "flag": "🇪🇹",
    "placeholder": "",
    "dialCode": "+251",
  },
  {
    "name": "Falkland Islands",
    "code": "FK",
    "flag": "🇫🇰",
    "placeholder": "",
    "dialCode": "+500",
  },
  {
    "name": "Faroe Islands",
    "code": "FO",
    "flag": "🇫🇴",
    "placeholder": "",
    "dialCode": "+298",
  },
  {
    "name": "Fiji",
    "code": "FJ",
    "flag": "🇫🇯",
    "placeholder": "",
    "dialCode": "+679",
  },
  {
    "name": "Finland",
    "code": "FI",
    "flag": "🇫🇮",
    "placeholder": "",
    "dialCode": "+358",
  },
  {
    "name": "France",
    "code": "FR",
    "flag": "🇫🇷",
    "placeholder": "",
    "dialCode": "+33",
  },
  {
    "name": "French Guiana",
    "code": "GF",
    "flag": "🇬🇫",
    "placeholder": "",
    "dialCode": "+594",
  },
  {
    "name": "French Polynesia",
    "code": "PF",
    "flag": "🇵🇫",
    "placeholder": "",
    "dialCode": "+689",
  },
  {
    "name": "Gabon",
    "code": "GA",
    "flag": "🇬🇦",
    "placeholder": "",
    "dialCode": "+241",
  },
  {
    "name": "Gambia",
    "code": "GM",
    "flag": "🇬🇲",
    "placeholder": "",
    "dialCode": "+220",
  },
  {
    "name": "Georgia",
    "code": "GE",
    "flag": "🇬🇪",
    "placeholder": "",
    "dialCode": "+995",
  },
  {
    "name": "Germany",
    "code": "DE",
    "flag": "🇩🇪",
    "placeholder": "",
    "dialCode": "+49",
  },
  {
    "name": "Ghana",
    "code": "GH",
    "flag": "🇬🇭",
    "placeholder": "",
    "dialCode": "+233",
  },
  {
    "name": "Gibraltar",
    "code": "GI",
    "flag": "🇬🇮",
    "placeholder": "",
    "dialCode": "+350",
  },
  {
    "name": "Greece",
    "code": "GR",
    "flag": "🇬🇷",
    "placeholder": "",
    "dialCode": "+30",
  },
  {
    "name": "Greenland",
    "code": "GL",
    "flag": "🇬🇱",
    "placeholder": "",
    "dialCode": "+299",
  },
  {
    "name": "Grenada",
    "code": "GD",
    "flag": "🇬🇩",
    "placeholder": "",
    "dialCode": "+1473",
  },
  {
    "name": "Guadeloupe",
    "code": "GP",
    "flag": "🇬🇵",
    "placeholder": "",
    "dialCode": "+590",
  },
  {
    "name": "Guam",
    "code": "GU",
    "flag": "🇬🇺",
    "placeholder": "",
    "dialCode": "+1671",
  },
  {
    "name": "Guatemala",
    "code": "GT",
    "flag": "🇬🇹",
    "placeholder": "",
    "dialCode": "+502",
  },
  {
    "name": "Guernsey",
    "code": "GG",
    "flag": "🇬🇬",
    "placeholder": "",
    "dialCode": "+44",
  },
  {
    "name": "Guinea",
    "code": "GN",
    "flag": "🇬🇳",
    "placeholder": "",
    "dialCode": "+224",
  },
  {
    "name": "Guinea-Bissau",
    "code": "GW",
    "flag": "🇬🇼",
    "placeholder": "",
    "dialCode": "+245",
  },
  {
    "name": "Guyana",
    "code": "GY",
    "flag": "🇬🇾",
    "placeholder": "",
    "dialCode": "+592",
  },
  {
    "name": "Haiti",
    "code": "HT",
    "flag": "🇭🇹",
    "placeholder": "",
    "dialCode": "+509",
  },
  {
    "name": "Honduras",
    "code": "HN",
    "flag": "🇭🇳",
    "placeholder": "",
    "dialCode": "+504",
  },
  {
    "name": "Hong Kong SAR China",
    "code": "HK",
    "flag": "🇭🇰",
    "placeholder": "",
    "dialCode": "+852",
  },
  {
    "name": "Hungary",
    "code": "HU",
    "flag": "🇭🇺",
    "placeholder": "",
    "dialCode": "+36",
  },
  {
    "name": "Iceland",
    "code": "IS",
    "flag": "🇮🇸",
    "placeholder": "",
    "dialCode": "+354",
  },
  {
    "name": "India",
    "code": "IN",
    "flag": "🇮🇳",
    "placeholder": "98765 43210",
    "dialCode": "+91",
  },
  {
    "name": "Indonesia",
    "code": "ID",
    "flag": "🇮🇩",
    "placeholder": "",
    "dialCode": "+62",
  },
  {
    "name": "Iran",
    "code": "IR",
    "flag": "🇮🇷",
    "placeholder": "",
    "dialCode": "+98",
  },
  {
    "name": "Iraq",
    "code": "IQ",
    "flag": "🇮🇶",
    "placeholder": "",
    "dialCode": "+964",
  },
  {
    "name": "Ireland",
    "code": "IE",
    "flag": "🇮🇪",
    "placeholder": "",
    "dialCode": "+353",
  },
  {
    "name": "Isle of Man",
    "code": "IM",
    "flag": "🇮🇲",
    "placeholder": "",
    "dialCode": "+44",
  },
  {
    "name": "Israel",
    "code": "IL",
    "flag": "🇮🇱",
    "placeholder": "",
    "dialCode": "+972",
  },
  {
    "name": "Italy",
    "code": "IT",
    "flag": "🇮🇹",
    "placeholder": "",
    "dialCode": "+39",
  },
  {
    "name": "Jamaica",
    "code": "JM",
    "flag": "🇯🇲",
    "placeholder": "",
    "dialCode": "+1 876",
  },
  {
    "name": "Japan",
    "code": "JP",
    "flag": "🇯🇵",
    "placeholder": "",
    "dialCode": "+81",
  },
  {
    "name": "Jersey",
    "code": "JE",
    "flag": "🇯🇪",
    "placeholder": "",
    "dialCode": "+44",
  },
  {
    "name": "Jordan",
    "code": "JO",
    "flag": "🇯🇴",
    "placeholder": "",
    "dialCode": "+962",
  },
  {
    "name": "Kazakhstan",
    "code": "KZ",
    "flag": "🇰🇿",
    "placeholder": "",
    "dialCode": "+7",
  },
  {
    "name": "Kenya",
    "code": "KE",
    "flag": "🇰🇪",
    "placeholder": "",
    "dialCode": "+254",
  },
  {
    "name": "Kiribati",
    "code": "KI",
    "flag": "🇰🇮",
    "placeholder": "",
    "dialCode": "+686",
  },
  {
    "name": "Kosovo",
    "code": "XK",
    "flag": "🇽🇰",
    "placeholder": "",
    "dialCode": "+383",
  },
  {
    "name": "Kuwait",
    "code": "KW",
    "flag": "🇰🇼",
    "placeholder": "",
    "dialCode": "+965",
  },
  {
    "name": "Kyrgyzstan",
    "code": "KG",
    "flag": "🇰🇬",
    "placeholder": "",
    "dialCode": "+996",
  },
  {
    "name": "Laos",
    "code": "LA",
    "flag": "🇱🇦",
    "placeholder": "",
    "dialCode": "+856",
  },
  {
    "name": "Latvia",
    "code": "LV",
    "flag": "🇱🇻",
    "placeholder": "",
    "dialCode": "+371",
  },
  {
    "name": "Lebanon",
    "code": "LB",
    "flag": "🇱🇧",
    "placeholder": "",
    "dialCode": "+961",
  },
  {
    "name": "Lesotho",
    "code": "LS",
    "flag": "🇱🇸",
    "placeholder": "",
    "dialCode": "+266",
  },
  {
    "name": "Liberia",
    "code": "LR",
    "flag": "🇱🇷",
    "placeholder": "",
    "dialCode": "+231",
  },
  {
    "name": "Libya",
    "code": "LY",
    "flag": "🇱🇾",
    "placeholder": "",
    "dialCode": "+218",
  },
  {
    "name": "Liechtenstein",
    "code": "LI",
    "flag": "🇱🇮",
    "placeholder": "",
    "dialCode": "+423",
  },
  {
    "name": "Lithuania",
    "code": "LT",
    "flag": "🇱🇹",
    "placeholder": "",
    "dialCode": "+370",
  },
  {
    "name": "Luxembourg",
    "code": "LU",
    "flag": "🇱🇺",
    "placeholder": "",
    "dialCode": "+352",
  },
  {
    "name": "Macao SAR China",
    "code": "MO",
    "flag": "🇲🇴",
    "placeholder": "",
    "dialCode": "+853",
  },
  {
    "name": "Madagascar",
    "code": "MG",
    "flag": "🇲🇬",
    "placeholder": "",
    "dialCode": "+261",
  },
  {
    "name": "Malawi",
    "code": "MW",
    "flag": "🇲🇼",
    "placeholder": "",
    "dialCode": "+265",
  },
  {
    "name": "Malaysia",
    "code": "MY",
    "flag": "🇲🇾",
    "placeholder": "",
    "dialCode": "+60",
  },
  {
    "name": "Maldives",
    "code": "MV",
    "flag": "🇲🇻",
    "placeholder": "",
    "dialCode": "+960",
  },
  {
    "name": "Mali",
    "code": "ML",
    "flag": "🇲🇱",
    "placeholder": "",
    "dialCode": "+223",
  },
  {
    "name": "Malta",
    "code": "MT",
    "flag": "🇲🇹",
    "placeholder": "",
    "dialCode": "+356",
  },
  {
    "name": "Marshall Islands",
    "code": "MH",
    "flag": "🇲🇭",
    "placeholder": "",
    "dialCode": "+692",
  },
  {
    "name": "Martinique",
    "code": "MQ",
    "flag": "🇲🇶",
    "placeholder": "",
    "dialCode": "+596",
  },
  {
    "name": "Mauritania",
    "code": "MR",
    "flag": "🇲🇷",
    "placeholder": "",
    "dialCode": "+222",
  },
  {
    "name": "Mauritius",
    "code": "MU",
    "flag": "🇲🇺",
    "placeholder": "",
    "dialCode": "+230",
  },
  {
    "name": "Mayotte",
    "code": "YT",
    "flag": "🇾🇹",
    "placeholder": "",
    "dialCode": "+262",
  },
  {
    "name": "Mexico",
    "code": "MX",
    "flag": "🇲🇽",
    "placeholder": "",
    "dialCode": "+52",
  },
  {
    "name": "Micronesia",
    "code": "FM",
    "flag": "🇫🇲",
    "placeholder": "",
    "dialCode": "+691",
  },
  {
    "name": "Moldova",
    "code": "MD",
    "flag": "🇲🇩",
    "placeholder": "",
    "dialCode": "+373",
  },
  {
    "name": "Monaco",
    "code": "MC",
    "flag": "🇲🇨",
    "placeholder": "",
    "dialCode": "+377",
  },
  {
    "name": "Mongolia",
    "code": "MN",
    "flag": "🇲🇳",
    "placeholder": "",
    "dialCode": "+976",
  },
  {
    "name": "Montenegro",
    "code": "ME",
    "flag": "🇲🇪",
    "placeholder": "",
    "dialCode": "+382",
  },
  {
    "name": "Montserrat",
    "code": "MS",
    "flag": "🇲🇸",
    "placeholder": "",
    "dialCode": "+1 664",
  },
  {
    "name": "Morocco",
    "code": "MA",
    "flag": "🇲🇦",
    "placeholder": "",
    "dialCode": "+212",
  },
  {
    "name": "Mozambique",
    "code": "MZ",
    "flag": "🇲🇿",
    "placeholder": "",
    "dialCode": "+258",
  },
  {
    "name": "Myanmar (Burma)",
    "code": "MM",
    "flag": "🇲🇲",
    "placeholder": "",
    "dialCode": "+95",
  },
  {
    "name": "Namibia",
    "code": "NA",
    "flag": "🇳🇦",
    "placeholder": "",
    "dialCode": "+264",
  },
  {
    "name": "Nauru",
    "code": "NR",
    "flag": "🇳🇷",
    "placeholder": "",
    "dialCode": "+674",
  },
  {
    "name": "Nepal",
    "code": "NP",
    "flag": "🇳🇵",
    "placeholder": "",
    "dialCode": "+977",
  },
  {
    "name": "Netherlands",
    "code": "NL",
    "flag": "🇳🇱",
    "placeholder": "",
    "dialCode": "+31",
  },
  {
    "name": "New Caledonia",
    "code": "NC",
    "flag": "🇳🇨",
    "placeholder": "",
    "dialCode": "+687",
  },
  {
    "name": "New Zealand",
    "code": "NZ",
    "flag": "🇳🇿",
    "placeholder": "",
    "dialCode": "+64",
  },
  {
    "name": "Nicaragua",
    "code": "NI",
    "flag": "🇳🇮",
    "placeholder": "",
    "dialCode": "+505",
  },
  {
    "name": "Niger",
    "code": "NE",
    "flag": "🇳🇪",
    "placeholder": "",
    "dialCode": "+227",
  },
  {
    "name": "Nigeria",
    "code": "NG",
    "flag": "🇳🇬",
    "placeholder": "",
    "dialCode": "+234",
  },
  {
    "name": "Niue",
    "code": "NU",
    "flag": "🇳🇺",
    "placeholder": "",
    "dialCode": "+683",
  },
  {
    "name": "Norfolk Island",
    "code": "NF",
    "flag": "🇳🇫",
    "placeholder": "",
    "dialCode": "+672",
  },
  {
    "name": "North Korea",
    "code": "KP",
    "flag": "🇰🇵",
    "placeholder": "",
    "dialCode": "+850",
  },
  {
    "name": "Northern Mariana Islands",
    "code": "MP",
    "flag": "🇲🇵",
    "placeholder": "",
    "dialCode": "+1 670",
  },
  {
    "name": "Norway",
    "code": "NO",
    "flag": "🇳🇴",
    "placeholder": "",
    "dialCode": "+47",
  },
  {
    "name": "Oman",
    "code": "OM",
    "flag": "🇴🇲",
    "placeholder": "",
    "dialCode": "+968",
  },
  {
    "name": "Pakistan",
    "code": "PK",
    "flag": "🇵🇰",
    "placeholder": "",
    "dialCode": "+92",
  },
  {
    "name": "Palau",
    "code": "PW",
    "flag": "🇵🇼",
    "placeholder": "",
    "dialCode": "+680",
  },
  {
    "name": "Palestinian Territories",
    "code": "PS",
    "flag": "🇵🇸",
    "placeholder": "",
    "dialCode": "+970",
  },
  {
    "name": "Panama",
    "code": "PA",
    "flag": "🇵🇦",
    "placeholder": "",
    "dialCode": "+507",
  },
  {
    "name": "Papua New Guinea",
    "code": "PG",
    "flag": "🇵🇬",
    "placeholder": "",
    "dialCode": "+675",
  },
  {
    "name": "Paraguay",
    "code": "PY",
    "flag": "🇵🇾",
    "placeholder": "",
    "dialCode": "+595",
  },
  {
    "name": "Peru",
    "code": "PE",
    "flag": "🇵🇪",
    "placeholder": "",
    "dialCode": "+51",
  },
  {
    "name": "Philippines",
    "code": "PH",
    "flag": "🇵🇭",
    "placeholder": "",
    "dialCode": "+63",
  },
  {
    "name": "Pitcairn Islands",
    "code": "PN",
    "flag": "🇵🇳",
    "placeholder": "",
    "dialCode": "+64",
  },
  {
    "name": "Poland",
    "code": "PL",
    "flag": "🇵🇱",
    "placeholder": "",
    "dialCode": "+48",
  },
  {
    "name": "Portugal",
    "code": "PT",
    "flag": "🇵🇹",
    "placeholder": "",
    "dialCode": "+351",
  },
  {
    "name": "Puerto Rico",
    "code": "PR",
    "flag": "🇵🇷",
    "placeholder": "",
    "dialCode": "+1 787",
  },
  {
    "name": "Qatar",
    "code": "QA",
    "flag": "🇶🇦",
    "placeholder": "",
    "dialCode": "+974",
  },
  {
    "name": "Réunion",
    "code": "RE",
    "flag": "🇷🇪",
    "placeholder": "",
    "dialCode": "+262",
  },
  {
    "name": "Romania",
    "code": "RO",
    "flag": "🇷🇴",
    "placeholder": "",
    "dialCode": "+40",
  },
  {
    "name": "Russia",
    "code": "RU",
    "flag": "🇷🇺",
    "placeholder": "",
    "dialCode": "+7",
  },
  {
    "name": "Rwanda",
    "code": "RW",
    "flag": "🇷🇼",
    "placeholder": "",
    "dialCode": "+250",
  },
  {
    "name": "Saint Helena",
    "code": "SH",
    "flag": "🇸🇭",
    "placeholder": "",
    "dialCode": "+290",
  },
  {
    "name": "Saint Kitts & Nevis",
    "code": "KN",
    "flag": "🇰🇳",
    "placeholder": "",
    "dialCode": "+1 869",
  },
  {
    "name": "Saint Lucia",
    "code": "LC",
    "flag": "🇱🇨",
    "placeholder": "",
    "dialCode": "+1 758",
  },
  {
    "name": "Saint Pierre & Miquelon",
    "code": "PM",
    "flag": "🇵🇲",
    "placeholder": "",
    "dialCode": "+508",
  },
  {
    "name": "Samoa",
    "code": "WS",
    "flag": "🇼🇸",
    "placeholder": "",
    "dialCode": "+685",
  },
  {
    "name": "San Marino",
    "code": "SM",
    "flag": "🇸🇲",
    "placeholder": "",
    "dialCode": "+378",
  },
  {
    "name": "Sao Tome & Principe",
    "code": "ST",
    "flag": "🇸🇹",
    "placeholder": "",
    "dialCode": "+239",
  },
  {
    "name": "Saudi Arabia",
    "code": "SA",
    "flag": "🇸🇦",
    "placeholder": "",
    "dialCode": "+966",
  },
  {
    "name": "Senegal",
    "code": "SN",
    "flag": "🇸🇳",
    "placeholder": "",
    "dialCode": "+221",
  },
  {
    "name": "Serbia",
    "code": "RS",
    "flag": "🇷🇸",
    "placeholder": "",
    "dialCode": "+381",
  },
  {
    "name": "Seychelles",
    "code": "SC",
    "flag": "🇸🇨",
    "placeholder": "",
    "dialCode": "+248",
  },
  {
    "name": "Sierra Leone",
    "code": "SL",
    "flag": "🇸🇱",
    "placeholder": "",
    "dialCode": "+232",
  },
  {
    "name": "Singapore",
    "code": "SG",
    "flag": "🇸🇬",
    "placeholder": "9123 4567",
    "dialCode": "+65",
  },
  {
    "name": "Sint Maarten",
    "code": "SX",
    "flag": "🇸🇽",
    "placeholder": "",
    "dialCode": "+1 721",
  },
  {
    "name": "Slovakia",
    "code": "SK",
    "flag": "🇸🇰",
    "placeholder": "",
    "dialCode": "+421",
  },
  {
    "name": "Slovenia",
    "code": "SI",
    "flag": "🇸🇮",
    "placeholder": "",
    "dialCode": "+386",
  },
  {
    "name": "Solomon Islands",
    "code": "SB",
    "flag": "🇸🇧",
    "placeholder": "",
    "dialCode": "+677",
  },
  {
    "name": "Somalia",
    "code": "SO",
    "flag": "🇸🇴",
    "placeholder": "",
    "dialCode": "+252",
  },
  {
    "name": "South Africa",
    "code": "ZA",
    "flag": "🇿🇦",
    "placeholder": "",
    "dialCode": "+27",
  },
  {
    "name": "South Korea",
    "code": "KR",
    "flag": "🇰🇷",
    "placeholder": "",
    "dialCode": "+82",
  },
  {
    "name": "South Sudan",
    "code": "SS",
    "flag": "🇸🇸",
    "placeholder": "",
    "dialCode": "+211",
  },
  {
    "name": "Spain",
    "code": "ES",
    "flag": "🇪🇸",
    "placeholder": "",
    "dialCode": "+34",
  },
  {
    "name": "Sri Lanka",
    "code": "LK",
    "flag": "🇱🇰",
    "placeholder": "",
    "dialCode": "+94",
  },
  {
    "name": "Sudan",
    "code": "SD",
    "flag": "🇸🇩",
    "placeholder": "",
    "dialCode": "+249",
  },
  {
    "name": "Suriname",
    "code": "SR",
    "flag": "🇸🇷",
    "placeholder": "",
    "dialCode": "+597",
  },
  {
    "name": "Sweden",
    "code": "SE",
    "flag": "🇸🇪",
    "placeholder": "",
    "dialCode": "+46",
  },
  {
    "name": "Switzerland",
    "code": "CH",
    "flag": "🇨🇭",
    "placeholder": "",
    "dialCode": "+41",
  },
  {
    "name": "Syria",
    "code": "SY",
    "flag": "🇸🇾",
    "placeholder": "",
    "dialCode": "+963",
  },
  {
    "name": "Taiwan",
    "code": "TW",
    "flag": "🇹🇼",
    "placeholder": "",
    "dialCode": "+886",
  },
  {
    "name": "Tajikistan",
    "code": "TJ",
    "flag": "🇹🇯",
    "placeholder": "",
    "dialCode": "+992",
  },
  {
    "name": "Tanzania",
    "code": "TZ",
    "flag": "🇹🇿",
    "placeholder": "",
    "dialCode": "+255",
  },
  {
    "name": "Thailand",
    "code": "TH",
    "flag": "🇹🇭",
    "placeholder": "081 234 5678",
    "dialCode": "+66",
  },
  {
    "name": "Timor-Leste",
    "code": "TL",
    "flag": "🇹🇱",
    "placeholder": "",
    "dialCode": "+670",
  },
  {
    "name": "Togo",
    "code": "TG",
    "flag": "🇹🇬",
    "placeholder": "",
    "dialCode": "+228",
  },
  {
    "name": "Tokelau",
    "code": "TK",
    "flag": "🇹🇰",
    "placeholder": "",
    "dialCode": "+690",
  },
  {
    "name": "Tonga",
    "code": "TO",
    "flag": "🇹🇴",
    "placeholder": "",
    "dialCode": "+676",
  },
  {
    "name": "Trinidad & Tobago",
    "code": "TT",
    "flag": "🇹🇹",
    "placeholder": "",
    "dialCode": "+1 868",
  },
  {
    "name": "Tunisia",
    "code": "TN",
    "flag": "🇹🇳",
    "placeholder": "",
    "dialCode": "+216",
  },
  {
    "name": "Turkey",
    "code": "TR",
    "flag": "🇹🇷",
    "placeholder": "",
    "dialCode": "+90",
  },
  {
    "name": "Turkmenistan",
    "code": "TM",
    "flag": "🇹🇲",
    "placeholder": "",
    "dialCode": "+993",
  },
  {
    "name": "Turks & Caicos Islands",
    "code": "TC",
    "flag": "🇹🇨",
    "placeholder": "",
    "dialCode": "+1 649",
  },
  {
    "name": "Tuvalu",
    "code": "TV",
    "flag": "🇹🇻",
    "placeholder": "",
    "dialCode": "+688",
  },
  {
    "name": "Uganda",
    "code": "UG",
    "flag": "🇺🇬",
    "placeholder": "",
    "dialCode": "+256",
  },
  {
    "name": "Ukraine",
    "code": "UA",
    "flag": "🇺🇦",
    "placeholder": "",
    "dialCode": "+380",
  },
  {
    "name": "United Arab Emirates",
    "code": "AE",
    "flag": "🇦🇪",
    "placeholder": "",
    "dialCode": "+971",
  },
  {
    "name": "United Kingdom",
    "code": "GB",
    "flag": "🇬🇧",
    "placeholder": "07123 456789",
    "dialCode": "+44",
  },
  {
    "name": "United States",
    "code": "US",
    "flag": "🇺🇸",
    "placeholder": "(123) 456-7890",
    "dialCode": "+1",
  },
  {
    "name": "Uruguay",
    "code": "UY",
    "flag": "🇺🇾",
    "placeholder": "",
    "dialCode": "+598",
  },
  {
    "name": "Uzbekistan",
    "code": "UZ",
    "flag": "🇺🇿",
    "placeholder": "",
    "dialCode": "+998",
  },
  {
    "name": "Vanuatu",
    "code": "VU",
    "flag": "🇻🇺",
    "placeholder": "",
    "dialCode": "+678",
  },
  {
    "name": "Vatican City",
    "code": "VA",
    "flag": "🇻🇦",
    "placeholder": "",
    "dialCode": "+379",
  },
  {
    "name": "Venezuela",
    "code": "VE",
    "flag": "🇻🇪",
    "placeholder": "",
    "dialCode": "+58",
  },
  {
    "name": "Vietnam",
    "code": "VN",
    "flag": "🇻🇳",
    "placeholder": "",
    "dialCode": "+84",
  },
  {
    "name": "Wallis & Futuna",
    "code": "WF",
    "flag": "🇼🇫",
    "placeholder": "",
    "dialCode": "+681",
  },
]
