import { environment } from '../environments/environment';
import currencies from '../assets/data/currencies.json'

export interface Currency {
  symbol: string,
  name: string,
  "symbol_native": string,
  "decimal_digits": number,
  "code": string,
}

export interface Country {
  name: string,
  code: string,
  flag: string,
  unicode: string,
  placeholder: string,
  dialCode: string,
  image: string,
}

export const DEFAULT_TOAST_DURATION = 2000;
export const PRIVATE_API = `${environment.apiBaseUrl}/api/v1`;
export const PUBLIC_API = environment.apiBaseUrl;
export const CURRENCIES: Currency[] = currencies;
export const CURRENCIES_CODES: string[] = currencies.map(currency => currency.code);
export const PHONE_MASKS: { [key: string]: any } = {
  'AF': {
    mask: [
      '0',  /\d/, /\d/, ' ', /\d/, /\d/, /\d/, ' ', /\d/, /\d/, /\d/, /\d/,
    ],
    autocomplete: 'tel',
    overwriteMode: 'shift',
  },
  'PK': {
    mask: [
      '0', '3', /\d/, /\d/, ' ', /\d/, /\d/, /\d/, /\d/, /\d/, /\d/, /\d/,
    ],
    autocomplete: 'tel',
    overwriteMode: 'shift',
  },
  'IN': {
    mask: [
      /[9|8|7]/, /\d/, /\d/, /\d/, /\d/, ' ', /\d/, /\d/, /\d/, /\d/, /\d/,
    ],
    autocomplete: 'tel',
    overwriteMode: 'shift',
  },
  'US': {
    mask: [
      '(', /\d/, /\d/, /\d/, ')', ' ', /\d/, /\d/, /\d/, '-', /\d/, /\d/, /\d/, /\d/,
    ],
    autocomplete: 'tel',
    overwriteMode: 'shift',
  },
  'GB': {
    mask: [
      '0', '7', /\d/, /\d/, /\d/, ' ', /\d/, /\d/, /\d/, /\d/, /\d/, /\d/,
    ],
    autocomplete: 'tel',
    overwriteMode: 'shift',
  },
  'TH': {
    mask: [
      '0', '8', /\d/, ' ', /\d/, /\d/, /\d/, ' ', /\d/, /\d/, /\d/, /\d/,
    ],
    autocomplete: 'tel',
    overwriteMode: 'shift',
  },
  'SG': {
    mask: [
      '9', /\d/, /\d/, /\d/, ' ', /\d/, /\d/, /\d/, /\d/,
    ],
    autocomplete: 'tel',
    overwriteMode: 'shift',
  },
  'CN': {
    mask: [
      '1', /\d/, /\d/, ' ', /\d/, /\d/, /\d/, /\d/, ' ', /\d/, /\d/, /\d/, /\d/,
    ],
    autocomplete: 'tel',
    overwriteMode: 'shift',
  },
};
export const countries = [
  {
    name: 'Pakistan',
    code: 'PK',
    dialCode: '+92',
    flag: '🇵🇰',
    placeholder: '0313 1245852',
  },
  {
    name: 'India',
    code: 'IN',
    dialCode: '+91',
    flag: '🇮🇳',
    placeholder: '98765 43210',
  },
  {
    name: 'United States',
    code: 'US',
    dialCode: '+1',
    flag: '🇺🇸',
    placeholder: '(123) 456-7890',
  },
  {
    name: 'United Kingdom',
    code: 'GB',
    dialCode: '+44',
    flag: '🇬🇧',
    placeholder: '07123 456789',
  },
  {
    name: 'Thailand',
    code: 'TH',
    dialCode: '+66',
    flag: '🇹🇭',
    placeholder: '081 234 5678',
  },
  {
    name: 'Singapore',
    code: 'SG',
    dialCode: '+65',
    flag: '🇸🇬',
    placeholder: '9123 4567',
  },
  {
    name: 'China',
    code: 'CN',
    dialCode: '+86',
    flag: '🇨🇳',
    placeholder: '138 1234 5678',
  },
];
export const COUNTRIES_WITH_CALLING_CODES: Country[] = [
  {
    "name": "Afghanistan",
    "code": "AF",
    "flag": "🇦🇫",
    "unicode": "U+1F1E6 U+1F1EB",
    "placeholder": "0xx yyy-yyyy",
    "dialCode": "+93",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AF.svg",
  },
  {
    "name": "Albania",
    "code": "AL",
    "flag": "🇦🇱",
    "unicode": "U+1F1E6 U+1F1F1",
    "placeholder": "",
    "dialCode": "+355",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AL.svg",
  },
  {
    "name": "Andorra",
    "code": "AD",
    "flag": "🇦🇩",
    "unicode": "U+1F1E6 U+1F1E9",
    "placeholder": "",
    "dialCode": "+376",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AD.svg",
  },
  {
    "name": "Angola",
    "code": "AO",
    "flag": "🇦🇴",
    "unicode": "U+1F1E6 U+1F1F4",
    "placeholder": "",
    "dialCode": "+244",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AO.svg",
  },
  {
    "name": "Anguilla",
    "code": "AI",
    "flag": "🇦🇮",
    "unicode": "U+1F1E6 U+1F1EE",
    "placeholder": "",
    "dialCode": "+1264",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AI.svg",
  },
  {
    "name": "Antarctica",
    "code": "AQ",
    "flag": "🇦🇶",
    "unicode": "U+1F1E6 U+1F1F6",
    "placeholder": "",
    "dialCode": "+672",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AQ.svg",
  },
  {
    "name": "Antigua & Barbuda",
    "code": "AG",
    "flag": "🇦🇬",
    "unicode": "U+1F1E6 U+1F1EC",
    "placeholder": "",
    "dialCode": "+1268",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AG.svg",
  },
  {
    "name": "Argentina",
    "code": "AR",
    "flag": "🇦🇷",
    "unicode": "U+1F1E6 U+1F1F7",
    "placeholder": "",
    "dialCode": "+54",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AR.svg",
  },
  {
    "name": "Armenia",
    "code": "AM",
    "flag": "🇦🇲",
    "unicode": "U+1F1E6 U+1F1F2",
    "placeholder": "",
    "dialCode": "+374",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AM.svg",
  },
  {
    "name": "Aruba",
    "code": "AW",
    "flag": "🇦🇼",
    "unicode": "U+1F1E6 U+1F1FC",
    "placeholder": "",
    "dialCode": "+297",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AW.svg",
  },
  {
    "name": "Ascension Island",
    "code": "AC",
    "flag": "🇦🇨",
    "unicode": "U+1F1E6 U+1F1E8",
    "placeholder": "",
    "dialCode": "+",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AC.svg",
  },
  {
    "name": "Australia",
    "code": "AU",
    "flag": "🇦🇺",
    "unicode": "U+1F1E6 U+1F1FA",
    "placeholder": "",
    "dialCode": "+61",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AU.svg",
  },
  {
    "name": "Austria",
    "code": "AT",
    "flag": "🇦🇹",
    "unicode": "U+1F1E6 U+1F1F9",
    "placeholder": "",
    "dialCode": "+43",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AT.svg",
  },
  {
    "name": "Azerbaijan",
    "code": "AZ",
    "flag": "🇦🇿",
    "unicode": "U+1F1E6 U+1F1FF",
    "placeholder": "",
    "dialCode": "+994",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AZ.svg",
  },
  {
    "name": "Bahamas",
    "code": "BS",
    "flag": "🇧🇸",
    "unicode": "U+1F1E7 U+1F1F8",
    "placeholder": "",
    "dialCode": "+1242",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BS.svg",
  },
  {
    "name": "Bahrain",
    "code": "BH",
    "flag": "🇧🇭",
    "unicode": "U+1F1E7 U+1F1ED",
    "placeholder": "",
    "dialCode": "+973",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BH.svg",
  },
  {
    "name": "Bangladesh",
    "code": "BD",
    "flag": "🇧🇩",
    "unicode": "U+1F1E7 U+1F1E9",
    "placeholder": "",
    "dialCode": "+880",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BD.svg",
  },
  {
    "name": "Barbados",
    "code": "BB",
    "flag": "🇧🇧",
    "unicode": "U+1F1E7 U+1F1E7",
    "placeholder": "",
    "dialCode": "+1246",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BB.svg",
  },
  {
    "name": "Belarus",
    "code": "BY",
    "flag": "🇧🇾",
    "unicode": "U+1F1E7 U+1F1FE",
    "placeholder": "",
    "dialCode": "+375",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BY.svg",
  },
  {
    "name": "Belgium",
    "code": "BE",
    "flag": "🇧🇪",
    "unicode": "U+1F1E7 U+1F1EA",
    "placeholder": "",
    "dialCode": "+32",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BE.svg",
  },
  {
    "name": "Belize",
    "code": "BZ",
    "flag": "🇧🇿",
    "unicode": "U+1F1E7 U+1F1FF",
    "placeholder": "",
    "dialCode": "+501",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BZ.svg",
  },
  {
    "name": "Benin",
    "code": "BJ",
    "flag": "🇧🇯",
    "unicode": "U+1F1E7 U+1F1EF",
    "placeholder": "",
    "dialCode": "+229",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BJ.svg",
  },
  {
    "name": "Bermuda",
    "code": "BM",
    "flag": "🇧🇲",
    "unicode": "U+1F1E7 U+1F1F2",
    "placeholder": "",
    "dialCode": "+1441",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BM.svg",
  },
  {
    "name": "Bhutan",
    "code": "BT",
    "flag": "🇧🇹",
    "unicode": "U+1F1E7 U+1F1F9",
    "placeholder": "",
    "dialCode": "+975",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BT.svg",
  },
  {
    "name": "Bolivia",
    "code": "BO",
    "flag": "🇧🇴",
    "unicode": "U+1F1E7 U+1F1F4",
    "placeholder": "",
    "dialCode": "+591",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BO.svg",
  },
  {
    "name": "Bosnia & Herzegovina",
    "code": "BA",
    "flag": "🇧🇦",
    "unicode": "U+1F1E7 U+1F1E6",
    "placeholder": "",
    "dialCode": "+387",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BA.svg",
  },
  {
    "name": "Botswana",
    "code": "BW",
    "flag": "🇧🇼",
    "unicode": "U+1F1E7 U+1F1FC",
    "placeholder": "",
    "dialCode": "+267",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BW.svg",
  },
  {
    "name": "Brazil",
    "code": "BR",
    "flag": "🇧🇷",
    "unicode": "U+1F1E7 U+1F1F7",
    "placeholder": "",
    "dialCode": "+55",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BR.svg",
  },
  {
    "name": "Brunei",
    "code": "BN",
    "flag": "🇧🇳",
    "unicode": "U+1F1E7 U+1F1F3",
    "placeholder": "",
    "dialCode": "+673",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BN.svg",
  },
  {
    "name": "Bulgaria",
    "code": "BG",
    "flag": "🇧🇬",
    "unicode": "U+1F1E7 U+1F1EC",
    "placeholder": "",
    "dialCode": "+359",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BG.svg",
  },
  {
    "name": "Burkina Faso",
    "code": "BF",
    "flag": "🇧🇫",
    "unicode": "U+1F1E7 U+1F1EB",
    "placeholder": "",
    "dialCode": "+226",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BF.svg",
  },
  {
    "name": "Burundi",
    "code": "BI",
    "flag": "🇧🇮",
    "unicode": "U+1F1E7 U+1F1EE",
    "placeholder": "",
    "dialCode": "+257",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BI.svg",
  },
  {
    "name": "Cabo Verde",
    "code": "CV",
    "flag": "🇨🇻",
    "unicode": "U+1F1E8 U+1F1FB",
    "placeholder": "",
    "dialCode": "+238",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CV.svg",
  },
  {
    "name": "Cambodia",
    "code": "KH",
    "flag": "🇰🇭",
    "unicode": "U+1F1F0 U+1F1ED",
    "placeholder": "",
    "dialCode": "+855",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KH.svg",
  },
  {
    "name": "Cameroon",
    "code": "CM",
    "flag": "🇨🇲",
    "unicode": "U+1F1E8 U+1F1F2",
    "placeholder": "",
    "dialCode": "+237",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CM.svg",
  },
  {
    "name": "Canada",
    "code": "CA",
    "flag": "🇨🇦",
    "unicode": "U+1F1E8 U+1F1E6",
    "placeholder": "",
    "dialCode": "+1",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CA.svg",
  },
  {
    "name": "Cayman Islands",
    "code": "KY",
    "flag": "🇰🇾",
    "unicode": "U+1F1F0 U+1F1FE",
    "placeholder": "",
    "dialCode": "+1345",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KY.svg",
  },
  {
    "name": "Central African Republic",
    "code": "CF",
    "flag": "🇨🇫",
    "unicode": "U+1F1E8 U+1F1EB",
    "placeholder": "",
    "dialCode": "+236",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CF.svg",
  },
  {
    "name": "Chad",
    "code": "TD",
    "flag": "🇹🇩",
    "unicode": "U+1F1F9 U+1F1E9",
    "placeholder": "",
    "dialCode": "+235",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TD.svg",
  },
  {
    "name": "Chile",
    "code": "CL",
    "flag": "🇨🇱",
    "unicode": "U+1F1E8 U+1F1F1",
    "placeholder": "",
    "dialCode": "+56",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CL.svg",
  },
  {
    "name": "China",
    "code": "CN",
    "flag": "🇨🇳",
    "unicode": "U+1F1E8 U+1F1F3",
    "placeholder": "",
    "dialCode": "+86",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CN.svg",
  },
  {
    "name": "Colombia",
    "code": "CO",
    "flag": "🇨🇴",
    "unicode": "U+1F1E8 U+1F1F4",
    "placeholder": "",
    "dialCode": "+57",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CO.svg",
  },
  {
    "name": "Comoros",
    "code": "KM",
    "flag": "🇰🇲",
    "unicode": "U+1F1F0 U+1F1F2",
    "placeholder": "",
    "dialCode": "+269",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KM.svg",
  },
  {
    "name": "Congo - Brazzaville",
    "code": "CG",
    "flag": "🇨🇬",
    "unicode": "U+1F1E8 U+1F1EC",
    "placeholder": "",
    "dialCode": "+242",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CG.svg",
  },
  {
    "name": "Congo - Kinshasa",
    "code": "CD",
    "flag": "🇨🇩",
    "unicode": "U+1F1E8 U+1F1E9",
    "placeholder": "",
    "dialCode": "+243",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CD.svg",
  },
  {
    "name": "Cook Islands",
    "code": "CK",
    "flag": "🇨🇰",
    "unicode": "U+1F1E8 U+1F1F0",
    "placeholder": "",
    "dialCode": "+682",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CK.svg",
  },
  {
    "name": "Costa Rica",
    "code": "CR",
    "flag": "🇨🇷",
    "unicode": "U+1F1E8 U+1F1F7",
    "placeholder": "",
    "dialCode": "+506",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CR.svg",
  },
  {
    "name": "Croatia",
    "code": "HR",
    "flag": "🇭🇷",
    "unicode": "U+1F1ED U+1F1F7",
    "placeholder": "",
    "dialCode": "+385",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HR.svg",
  },
  {
    "name": "Cuba",
    "code": "CU",
    "flag": "🇨🇺",
    "unicode": "U+1F1E8 U+1F1FA",
    "placeholder": "",
    "dialCode": "+53",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CU.svg",
  },
  {
    "name": "Curaçao",
    "code": "CW",
    "flag": "🇨🇼",
    "unicode": "U+1F1E8 U+1F1FC",
    "placeholder": "",
    "dialCode": "+599",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CW.svg",
  },
  {
    "name": "Cyprus",
    "code": "CY",
    "flag": "🇨🇾",
    "unicode": "U+1F1E8 U+1F1FE",
    "placeholder": "",
    "dialCode": "+357",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CY.svg",
  },
  {
    "name": "Czechia",
    "code": "CZ",
    "flag": "🇨🇿",
    "unicode": "U+1F1E8 U+1F1FF",
    "placeholder": "",
    "dialCode": "+420",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CZ.svg",
  },
  {
    "name": "Côte d’Ivoire",
    "code": "CI",
    "flag": "🇨🇮",
    "unicode": "U+1F1E8 U+1F1EE",
    "placeholder": "",
    "dialCode": "+225",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CI.svg",
  },
  {
    "name": "Denmark",
    "code": "DK",
    "flag": "🇩🇰",
    "unicode": "U+1F1E9 U+1F1F0",
    "placeholder": "",
    "dialCode": "+45",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DK.svg",
  },
  {
    "name": "Djibouti",
    "code": "DJ",
    "flag": "🇩🇯",
    "unicode": "U+1F1E9 U+1F1EF",
    "placeholder": "",
    "dialCode": "+253",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DJ.svg",
  },
  {
    "name": "Dominica",
    "code": "DM",
    "flag": "🇩🇲",
    "unicode": "U+1F1E9 U+1F1F2",
    "placeholder": "",
    "dialCode": "+1767",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DM.svg",
  },
  {
    "name": "Dominican Republic",
    "code": "DO",
    "flag": "🇩🇴",
    "unicode": "U+1F1E9 U+1F1F4",
    "placeholder": "",
    "dialCode": "+1 809, +1 829, +1 849",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DO.svg",
  },
  {
    "name": "Ecuador",
    "code": "EC",
    "flag": "🇪🇨",
    "unicode": "U+1F1EA U+1F1E8",
    "placeholder": "",
    "dialCode": "+593",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EC.svg",
  },
  {
    "name": "Egypt",
    "code": "EG",
    "flag": "🇪🇬",
    "unicode": "U+1F1EA U+1F1EC",
    "placeholder": "",
    "dialCode": "+20",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EG.svg",
  },
  {
    "name": "El Salvador",
    "code": "SV",
    "flag": "🇸🇻",
    "unicode": "U+1F1F8 U+1F1FB",
    "placeholder": "",
    "dialCode": "+503",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SV.svg",
  },
  {
    "name": "Equatorial Guinea",
    "code": "GQ",
    "flag": "🇬🇶",
    "unicode": "U+1F1EC U+1F1F6",
    "placeholder": "",
    "dialCode": "+240",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GQ.svg",
  },
  {
    "name": "Eritrea",
    "code": "ER",
    "flag": "🇪🇷",
    "unicode": "U+1F1EA U+1F1F7",
    "placeholder": "",
    "dialCode": "+291",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ER.svg",
  },
  {
    "name": "Estonia",
    "code": "EE",
    "flag": "🇪🇪",
    "unicode": "U+1F1EA U+1F1EA",
    "placeholder": "",
    "dialCode": "+372",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EE.svg",
  },
  {
    "name": "Eswatini",
    "code": "SZ",
    "flag": "🇸🇿",
    "unicode": "U+1F1F8 U+1F1FF",
    "placeholder": "",
    "dialCode": "+268",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SZ.svg",
  },
  {
    "name": "Ethiopia",
    "code": "ET",
    "flag": "🇪🇹",
    "unicode": "U+1F1EA U+1F1F9",
    "placeholder": "",
    "dialCode": "+251",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ET.svg",
  },
  {
    "name": "Falkland Islands",
    "code": "FK",
    "flag": "🇫🇰",
    "unicode": "U+1F1EB U+1F1F0",
    "placeholder": "",
    "dialCode": "+500",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FK.svg",
  },
  {
    "name": "Faroe Islands",
    "code": "FO",
    "flag": "🇫🇴",
    "unicode": "U+1F1EB U+1F1F4",
    "placeholder": "",
    "dialCode": "+298",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FO.svg",
  },
  {
    "name": "Fiji",
    "code": "FJ",
    "flag": "🇫🇯",
    "unicode": "U+1F1EB U+1F1EF",
    "placeholder": "",
    "dialCode": "+679",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FJ.svg",
  },
  {
    "name": "Finland",
    "code": "FI",
    "flag": "🇫🇮",
    "unicode": "U+1F1EB U+1F1EE",
    "placeholder": "",
    "dialCode": "+358",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FI.svg",
  },
  {
    "name": "France",
    "code": "FR",
    "flag": "🇫🇷",
    "unicode": "U+1F1EB U+1F1F7",
    "placeholder": "",
    "dialCode": "+33",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FR.svg",
  },
  {
    "name": "French Guiana",
    "code": "GF",
    "flag": "🇬🇫",
    "unicode": "U+1F1EC U+1F1EB",
    "placeholder": "",
    "dialCode": "+594",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GF.svg",
  },
  {
    "name": "French Polynesia",
    "code": "PF",
    "flag": "🇵🇫",
    "unicode": "U+1F1F5 U+1F1EB",
    "placeholder": "",
    "dialCode": "+689",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PF.svg",
  },
  {
    "name": "Gabon",
    "code": "GA",
    "flag": "🇬🇦",
    "unicode": "U+1F1EC U+1F1E6",
    "placeholder": "",
    "dialCode": "+241",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GA.svg",
  },
  {
    "name": "Gambia",
    "code": "GM",
    "flag": "🇬🇲",
    "unicode": "U+1F1EC U+1F1F2",
    "placeholder": "",
    "dialCode": "+220",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GM.svg",
  },
  {
    "name": "Georgia",
    "code": "GE",
    "flag": "🇬🇪",
    "unicode": "U+1F1EC U+1F1EA",
    "placeholder": "",
    "dialCode": "+995",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GE.svg",
  },
  {
    "name": "Germany",
    "code": "DE",
    "flag": "🇩🇪",
    "unicode": "U+1F1E9 U+1F1EA",
    "placeholder": "",
    "dialCode": "+49",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DE.svg",
  },
  {
    "name": "Ghana",
    "code": "GH",
    "flag": "🇬🇭",
    "unicode": "U+1F1EC U+1F1ED",
    "placeholder": "",
    "dialCode": "+233",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GH.svg",
  },
  {
    "name": "Gibraltar",
    "code": "GI",
    "flag": "🇬🇮",
    "unicode": "U+1F1EC U+1F1EE",
    "placeholder": "",
    "dialCode": "+350",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GI.svg",
  },
  {
    "name": "Greece",
    "code": "GR",
    "flag": "🇬🇷",
    "unicode": "U+1F1EC U+1F1F7",
    "placeholder": "",
    "dialCode": "+30",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GR.svg",
  },
  {
    "name": "Greenland",
    "code": "GL",
    "flag": "🇬🇱",
    "unicode": "U+1F1EC U+1F1F1",
    "placeholder": "",
    "dialCode": "+299",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GL.svg",
  },
  {
    "name": "Grenada",
    "code": "GD",
    "flag": "🇬🇩",
    "unicode": "U+1F1EC U+1F1E9",
    "placeholder": "",
    "dialCode": "+1473",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GD.svg",
  },
  {
    "name": "Guadeloupe",
    "code": "GP",
    "flag": "🇬🇵",
    "unicode": "U+1F1EC U+1F1F5",
    "placeholder": "",
    "dialCode": "+590",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GP.svg",
  },
  {
    "name": "Guam",
    "code": "GU",
    "flag": "🇬🇺",
    "unicode": "U+1F1EC U+1F1FA",
    "placeholder": "",
    "dialCode": "+1671",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GU.svg",
  },
  {
    "name": "Guatemala",
    "code": "GT",
    "flag": "🇬🇹",
    "unicode": "U+1F1EC U+1F1F9",
    "placeholder": "",
    "dialCode": "+502",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GT.svg",
  },
  {
    "name": "Guernsey",
    "code": "GG",
    "flag": "🇬🇬",
    "unicode": "U+1F1EC U+1F1EC",
    "placeholder": "",
    "dialCode": "+44",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GG.svg",
  },
  {
    "name": "Guinea",
    "code": "GN",
    "flag": "🇬🇳",
    "unicode": "U+1F1EC U+1F1F3",
    "placeholder": "",
    "dialCode": "+224",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GN.svg",
  },
  {
    "name": "Guinea-Bissau",
    "code": "GW",
    "flag": "🇬🇼",
    "unicode": "U+1F1EC U+1F1FC",
    "placeholder": "",
    "dialCode": "+245",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GW.svg",
  },
  {
    "name": "Guyana",
    "code": "GY",
    "flag": "🇬🇾",
    "unicode": "U+1F1EC U+1F1FE",
    "placeholder": "",
    "dialCode": "+592",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GY.svg",
  },
  {
    "name": "Haiti",
    "code": "HT",
    "flag": "🇭🇹",
    "unicode": "U+1F1ED U+1F1F9",
    "placeholder": "",
    "dialCode": "+509",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HT.svg",
  },
  {
    "name": "Honduras",
    "code": "HN",
    "flag": "🇭🇳",
    "unicode": "U+1F1ED U+1F1F3",
    "placeholder": "",
    "dialCode": "+504",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HN.svg",
  },
  {
    "name": "Hong Kong SAR China",
    "code": "HK",
    "flag": "🇭🇰",
    "unicode": "U+1F1ED U+1F1F0",
    "placeholder": "",
    "dialCode": "+852",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HK.svg",
  },
  {
    "name": "Hungary",
    "code": "HU",
    "flag": "🇭🇺",
    "unicode": "U+1F1ED U+1F1FA",
    "placeholder": "",
    "dialCode": "+36",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HU.svg",
  },
  {
    "name": "Iceland",
    "code": "IS",
    "flag": "🇮🇸",
    "unicode": "U+1F1EE U+1F1F8",
    "placeholder": "",
    "dialCode": "+354",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IS.svg",
  },
  {
    "name": "India",
    "code": "IN",
    "flag": "🇮🇳",
    "unicode": "U+1F1EE U+1F1F3",
    "placeholder": "",
    "dialCode": "+91",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IN.svg",
  },
  {
    "name": "Indonesia",
    "code": "ID",
    "flag": "🇮🇩",
    "unicode": "U+1F1EE U+1F1E9",
    "placeholder": "",
    "dialCode": "+62",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ID.svg",
  },
  {
    "name": "Iran",
    "code": "IR",
    "flag": "🇮🇷",
    "unicode": "U+1F1EE U+1F1F7",
    "placeholder": "",
    "dialCode": "+98",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IR.svg",
  },
  {
    "name": "Iraq",
    "code": "IQ",
    "flag": "🇮🇶",
    "unicode": "U+1F1EE U+1F1F6",
    "placeholder": "",
    "dialCode": "+964",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IQ.svg",
  },
  {
    "name": "Ireland",
    "code": "IE",
    "flag": "🇮🇪",
    "unicode": "U+1F1EE U+1F1EA",
    "placeholder": "",
    "dialCode": "+353",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IE.svg",
  },
  {
    "name": "Isle of Man",
    "code": "IM",
    "flag": "🇮🇲",
    "unicode": "U+1F1EE U+1F1F2",
    "placeholder": "",
    "dialCode": "+44",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IM.svg",
  },
  {
    "name": "Israel",
    "code": "IL",
    "flag": "🇮🇱",
    "unicode": "U+1F1EE U+1F1F1",
    "placeholder": "",
    "dialCode": "+972",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IL.svg",
  },
  {
    "name": "Italy",
    "code": "IT",
    "flag": "🇮🇹",
    "unicode": "U+1F1EE U+1F1F9",
    "placeholder": "",
    "dialCode": "+39",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IT.svg",
  },
  {
    "name": "Jamaica",
    "code": "JM",
    "flag": "🇯🇲",
    "unicode": "U+1F1EF U+1F1F2",
    "placeholder": "",
    "dialCode": "+1 876",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JM.svg",
  },
  {
    "name": "Japan",
    "code": "JP",
    "flag": "🇯🇵",
    "unicode": "U+1F1EF U+1F1F5",
    "placeholder": "",
    "dialCode": "+81",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JP.svg",
  },
  {
    "name": "Jersey",
    "code": "JE",
    "flag": "🇯🇪",
    "unicode": "U+1F1EF U+1F1EA",
    "placeholder": "",
    "dialCode": "+44",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JE.svg",
  },
  {
    "name": "Jordan",
    "code": "JO",
    "flag": "🇯🇴",
    "unicode": "U+1F1EF U+1F1F4",
    "placeholder": "",
    "dialCode": "+962",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JO.svg",
  },
  {
    "name": "Kazakhstan",
    "code": "KZ",
    "flag": "🇰🇿",
    "unicode": "U+1F1F0 U+1F1FF",
    "placeholder": "",
    "dialCode": "+7",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KZ.svg",
  },
  {
    "name": "Kenya",
    "code": "KE",
    "flag": "🇰🇪",
    "unicode": "U+1F1F0 U+1F1EA",
    "placeholder": "",
    "dialCode": "+254",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KE.svg",
  },
  {
    "name": "Kiribati",
    "code": "KI",
    "flag": "🇰🇮",
    "unicode": "U+1F1F0 U+1F1EE",
    "placeholder": "",
    "dialCode": "+686",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KI.svg",
  },
  {
    "name": "Kosovo",
    "code": "XK",
    "flag": "🇽🇰",
    "unicode": "U+1F1FD U+1F1F0",
    "placeholder": "",
    "dialCode": "+383",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/XK.svg",
  },
  {
    "name": "Kuwait",
    "code": "KW",
    "flag": "🇰🇼",
    "unicode": "U+1F1F0 U+1F1FC",
    "placeholder": "",
    "dialCode": "+965",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KW.svg",
  },
  {
    "name": "Kyrgyzstan",
    "code": "KG",
    "flag": "🇰🇬",
    "unicode": "U+1F1F0 U+1F1EC",
    "placeholder": "",
    "dialCode": "+996",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KG.svg",
  },
  {
    "name": "Laos",
    "code": "LA",
    "flag": "🇱🇦",
    "unicode": "U+1F1F1 U+1F1E6",
    "placeholder": "",
    "dialCode": "+856",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LA.svg",
  },
  {
    "name": "Latvia",
    "code": "LV",
    "flag": "🇱🇻",
    "unicode": "U+1F1F1 U+1F1FB",
    "placeholder": "",
    "dialCode": "+371",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LV.svg",
  },
  {
    "name": "Lebanon",
    "code": "LB",
    "flag": "🇱🇧",
    "unicode": "U+1F1F1 U+1F1E7",
    "placeholder": "",
    "dialCode": "+961",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LB.svg",
  },
  {
    "name": "Lesotho",
    "code": "LS",
    "flag": "🇱🇸",
    "unicode": "U+1F1F1 U+1F1F8",
    "placeholder": "",
    "dialCode": "+266",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LS.svg",
  },
  {
    "name": "Liberia",
    "code": "LR",
    "flag": "🇱🇷",
    "unicode": "U+1F1F1 U+1F1F7",
    "placeholder": "",
    "dialCode": "+231",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LR.svg",
  },
  {
    "name": "Libya",
    "code": "LY",
    "flag": "🇱🇾",
    "unicode": "U+1F1F1 U+1F1FE",
    "placeholder": "",
    "dialCode": "+218",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LY.svg",
  },
  {
    "name": "Liechtenstein",
    "code": "LI",
    "flag": "🇱🇮",
    "unicode": "U+1F1F1 U+1F1EE",
    "placeholder": "",
    "dialCode": "+423",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LI.svg",
  },
  {
    "name": "Lithuania",
    "code": "LT",
    "flag": "🇱🇹",
    "unicode": "U+1F1F1 U+1F1F9",
    "placeholder": "",
    "dialCode": "+370",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LT.svg",
  },
  {
    "name": "Luxembourg",
    "code": "LU",
    "flag": "🇱🇺",
    "unicode": "U+1F1F1 U+1F1FA",
    "placeholder": "",
    "dialCode": "+352",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LU.svg",
  },
  {
    "name": "Macao SAR China",
    "code": "MO",
    "flag": "🇲🇴",
    "unicode": "U+1F1F2 U+1F1F4",
    "placeholder": "",
    "dialCode": "+853",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MO.svg",
  },
  {
    "name": "Madagascar",
    "code": "MG",
    "flag": "🇲🇬",
    "unicode": "U+1F1F2 U+1F1EC",
    "placeholder": "",
    "dialCode": "+261",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MG.svg",
  },
  {
    "name": "Malawi",
    "code": "MW",
    "flag": "🇲🇼",
    "unicode": "U+1F1F2 U+1F1FC",
    "placeholder": "",
    "dialCode": "+265",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MW.svg",
  },
  {
    "name": "Malaysia",
    "code": "MY",
    "flag": "🇲🇾",
    "unicode": "U+1F1F2 U+1F1FE",
    "placeholder": "",
    "dialCode": "+60",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MY.svg",
  },
  {
    "name": "Maldives",
    "code": "MV",
    "flag": "🇲🇻",
    "unicode": "U+1F1F2 U+1F1FB",
    "placeholder": "",
    "dialCode": "+960",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MV.svg",
  },
  {
    "name": "Mali",
    "code": "ML",
    "flag": "🇲🇱",
    "unicode": "U+1F1F2 U+1F1F1",
    "placeholder": "",
    "dialCode": "+223",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ML.svg",
  },
  {
    "name": "Malta",
    "code": "MT",
    "flag": "🇲🇹",
    "unicode": "U+1F1F2 U+1F1F9",
    "placeholder": "",
    "dialCode": "+356",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MT.svg",
  },
  {
    "name": "Marshall Islands",
    "code": "MH",
    "flag": "🇲🇭",
    "unicode": "U+1F1F2 U+1F1ED",
    "placeholder": "",
    "dialCode": "+692",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MH.svg",
  },
  {
    "name": "Martinique",
    "code": "MQ",
    "flag": "🇲🇶",
    "unicode": "U+1F1F2 U+1F1F6",
    "placeholder": "",
    "dialCode": "+596",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MQ.svg",
  },
  {
    "name": "Mauritania",
    "code": "MR",
    "flag": "🇲🇷",
    "unicode": "U+1F1F2 U+1F1F7",
    "placeholder": "",
    "dialCode": "+222",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MR.svg",
  },
  {
    "name": "Mauritius",
    "code": "MU",
    "flag": "🇲🇺",
    "unicode": "U+1F1F2 U+1F1FA",
    "placeholder": "",
    "dialCode": "+230",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MU.svg",
  },
  {
    "name": "Mayotte",
    "code": "YT",
    "flag": "🇾🇹",
    "unicode": "U+1F1FE U+1F1F9",
    "placeholder": "",
    "dialCode": "+262",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/YT.svg",
  },
  {
    "name": "Mexico",
    "code": "MX",
    "flag": "🇲🇽",
    "unicode": "U+1F1F2 U+1F1FD",
    "placeholder": "",
    "dialCode": "+52",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MX.svg",
  },
  {
    "name": "Micronesia",
    "code": "FM",
    "flag": "🇫🇲",
    "unicode": "U+1F1EB U+1F1F2",
    "placeholder": "",
    "dialCode": "+691",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FM.svg",
  },
  {
    "name": "Moldova",
    "code": "MD",
    "flag": "🇲🇩",
    "unicode": "U+1F1F2 U+1F1E9",
    "placeholder": "",
    "dialCode": "+373",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MD.svg",
  },
  {
    "name": "Monaco",
    "code": "MC",
    "flag": "🇲🇨",
    "unicode": "U+1F1F2 U+1F1E8",
    "placeholder": "",
    "dialCode": "+377",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MC.svg",
  },
  {
    "name": "Mongolia",
    "code": "MN",
    "flag": "🇲🇳",
    "unicode": "U+1F1F2 U+1F1F3",
    "placeholder": "",
    "dialCode": "+976",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MN.svg",
  },
  {
    "name": "Montenegro",
    "code": "ME",
    "flag": "🇲🇪",
    "unicode": "U+1F1F2 U+1F1EA",
    "placeholder": "",
    "dialCode": "+382",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ME.svg",
  },
  {
    "name": "Montserrat",
    "code": "MS",
    "flag": "🇲🇸",
    "unicode": "U+1F1F2 U+1F1F8",
    "placeholder": "",
    "dialCode": "+1 664",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MS.svg",
  },
  {
    "name": "Morocco",
    "code": "MA",
    "flag": "🇲🇦",
    "unicode": "U+1F1F2 U+1F1E6",
    "placeholder": "",
    "dialCode": "+212",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MA.svg",
  },
  {
    "name": "Mozambique",
    "code": "MZ",
    "flag": "🇲🇿",
    "unicode": "U+1F1F2 U+1F1FF",
    "placeholder": "",
    "dialCode": "+258",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MZ.svg",
  },
  {
    "name": "Myanmar (Burma)",
    "code": "MM",
    "flag": "🇲🇲",
    "unicode": "U+1F1F2 U+1F1F2",
    "placeholder": "",
    "dialCode": "+95",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MM.svg",
  },
  {
    "name": "Namibia",
    "code": "NA",
    "flag": "🇳🇦",
    "unicode": "U+1F1F3 U+1F1E6",
    "placeholder": "",
    "dialCode": "+264",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NA.svg",
  },
  {
    "name": "Nauru",
    "code": "NR",
    "flag": "🇳🇷",
    "unicode": "U+1F1F3 U+1F1F7",
    "placeholder": "",
    "dialCode": "+674",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NR.svg",
  },
  {
    "name": "Nepal",
    "code": "NP",
    "flag": "🇳🇵",
    "unicode": "U+1F1F3 U+1F1F5",
    "placeholder": "",
    "dialCode": "+977",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NP.svg",
  },
  {
    "name": "Netherlands",
    "code": "NL",
    "flag": "🇳🇱",
    "unicode": "U+1F1F3 U+1F1F1",
    "placeholder": "",
    "dialCode": "+31",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NL.svg",
  },
  {
    "name": "New Caledonia",
    "code": "NC",
    "flag": "🇳🇨",
    "unicode": "U+1F1F3 U+1F1E8",
    "placeholder": "",
    "dialCode": "+687",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NC.svg",
  },
  {
    "name": "New Zealand",
    "code": "NZ",
    "flag": "🇳🇿",
    "unicode": "U+1F1F3 U+1F1FF",
    "placeholder": "",
    "dialCode": "+64",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NZ.svg",
  },
  {
    "name": "Nicaragua",
    "code": "NI",
    "flag": "🇳🇮",
    "unicode": "U+1F1F3 U+1F1EE",
    "placeholder": "",
    "dialCode": "+505",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NI.svg",
  },
  {
    "name": "Niger",
    "code": "NE",
    "flag": "🇳🇪",
    "unicode": "U+1F1F3 U+1F1EA",
    "placeholder": "",
    "dialCode": "+227",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NE.svg",
  },
  {
    "name": "Nigeria",
    "code": "NG",
    "flag": "🇳🇬",
    "unicode": "U+1F1F3 U+1F1EC",
    "placeholder": "",
    "dialCode": "+234",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NG.svg",
  },
  {
    "name": "Niue",
    "code": "NU",
    "flag": "🇳🇺",
    "unicode": "U+1F1F3 U+1F1FA",
    "placeholder": "",
    "dialCode": "+683",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NU.svg",
  },
  {
    "name": "Norfolk Island",
    "code": "NF",
    "flag": "🇳🇫",
    "unicode": "U+1F1F3 U+1F1EB",
    "placeholder": "",
    "dialCode": "+672",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NF.svg",
  },
  {
    "name": "North Korea",
    "code": "KP",
    "flag": "🇰🇵",
    "unicode": "U+1F1F0 U+1F1F5",
    "placeholder": "",
    "dialCode": "+850",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KP.svg",
  },
  {
    "name": "Northern Mariana Islands",
    "code": "MP",
    "flag": "🇲🇵",
    "unicode": "U+1F1F2 U+1F1F5",
    "placeholder": "",
    "dialCode": "+1 670",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MP.svg",
  },
  {
    "name": "Norway",
    "code": "NO",
    "flag": "🇳🇴",
    "unicode": "U+1F1F3 U+1F1F4",
    "placeholder": "",
    "dialCode": "+47",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NO.svg",
  },
  {
    "name": "Oman",
    "code": "OM",
    "flag": "🇴🇲",
    "unicode": "U+1F1F4 U+1F1F2",
    "placeholder": "",
    "dialCode": "+968",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/OM.svg",
  },
  {
    "name": "Pakistan",
    "code": "PK",
    "flag": "🇵🇰",
    "unicode": "U+1F1F5 U+1F1F0",
    "placeholder": "",
    "dialCode": "+92",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PK.svg",
  },
  {
    "name": "Palau",
    "code": "PW",
    "flag": "🇵🇼",
    "unicode": "U+1F1F5 U+1F1FC",
    "placeholder": "",
    "dialCode": "+680",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PW.svg",
  },
  {
    "name": "Palestinian Territories",
    "code": "PS",
    "flag": "🇵🇸",
    "unicode": "U+1F1F5 U+1F1F8",
    "placeholder": "",
    "dialCode": "+970",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PS.svg",
  },
  {
    "name": "Panama",
    "code": "PA",
    "flag": "🇵🇦",
    "unicode": "U+1F1F5 U+1F1E6",
    "placeholder": "",
    "dialCode": "+507",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PA.svg",
  },
  {
    "name": "Papua New Guinea",
    "code": "PG",
    "flag": "🇵🇬",
    "unicode": "U+1F1F5 U+1F1EC",
    "placeholder": "",
    "dialCode": "+675",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PG.svg",
  },
  {
    "name": "Paraguay",
    "code": "PY",
    "flag": "🇵🇾",
    "unicode": "U+1F1F5 U+1F1FE",
    "placeholder": "",
    "dialCode": "+595",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PY.svg",
  },
  {
    "name": "Peru",
    "code": "PE",
    "flag": "🇵🇪",
    "unicode": "U+1F1F5 U+1F1EA",
    "placeholder": "",
    "dialCode": "+51",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PE.svg",
  },
  {
    "name": "Philippines",
    "code": "PH",
    "flag": "🇵🇭",
    "unicode": "U+1F1F5 U+1F1ED",
    "placeholder": "",
    "dialCode": "+63",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PH.svg",
  },
  {
    "name": "Pitcairn Islands",
    "code": "PN",
    "flag": "🇵🇳",
    "unicode": "U+1F1F5 U+1F1F3",
    "placeholder": "",
    "dialCode": "+64",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PN.svg",
  },
  {
    "name": "Poland",
    "code": "PL",
    "flag": "🇵🇱",
    "unicode": "U+1F1F5 U+1F1F1",
    "placeholder": "",
    "dialCode": "+48",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PL.svg",
  },
  {
    "name": "Portugal",
    "code": "PT",
    "flag": "🇵🇹",
    "unicode": "U+1F1F5 U+1F1F9",
    "placeholder": "",
    "dialCode": "+351",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PT.svg",
  },
  {
    "name": "Puerto Rico",
    "code": "PR",
    "flag": "🇵🇷",
    "unicode": "U+1F1F5 U+1F1F7",
    "placeholder": "",
    "dialCode": "+1 787",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PR.svg",
  },
  {
    "name": "Qatar",
    "code": "QA",
    "flag": "🇶🇦",
    "unicode": "U+1F1F6 U+1F1E6",
    "placeholder": "",
    "dialCode": "+974",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/QA.svg",
  },
  {
    "name": "Réunion",
    "code": "RE",
    "flag": "🇷🇪",
    "unicode": "U+1F1F7 U+1F1EA",
    "placeholder": "",
    "dialCode": "+262",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RE.svg",
  },
  {
    "name": "Romania",
    "code": "RO",
    "flag": "🇷🇴",
    "unicode": "U+1F1F7 U+1F1F4",
    "placeholder": "",
    "dialCode": "+40",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RO.svg",
  },
  {
    "name": "Russia",
    "code": "RU",
    "flag": "🇷🇺",
    "unicode": "U+1F1F7 U+1F1FA",
    "placeholder": "",
    "dialCode": "+7",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RU.svg",
  },
  {
    "name": "Rwanda",
    "code": "RW",
    "flag": "🇷🇼",
    "unicode": "U+1F1F7 U+1F1FC",
    "placeholder": "",
    "dialCode": "+250",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RW.svg",
  },
  {
    "name": "Saint Helena",
    "code": "SH",
    "flag": "🇸🇭",
    "unicode": "U+1F1F8 U+1F1ED",
    "placeholder": "",
    "dialCode": "+290",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SH.svg",
  },
  {
    "name": "Saint Kitts & Nevis",
    "code": "KN",
    "flag": "🇰🇳",
    "unicode": "U+1F1F0 U+1F1F3",
    "placeholder": "",
    "dialCode": "+1 869",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KN.svg",
  },
  {
    "name": "Saint Lucia",
    "code": "LC",
    "flag": "🇱🇨",
    "unicode": "U+1F1F1 U+1F1E8",
    "placeholder": "",
    "dialCode": "+1 758",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LC.svg",
  },
  {
    "name": "Saint Pierre & Miquelon",
    "code": "PM",
    "flag": "🇵🇲",
    "unicode": "U+1F1F5 U+1F1F2",
    "placeholder": "",
    "dialCode": "+508",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PM.svg",
  },
  {
    "name": "Samoa",
    "code": "WS",
    "flag": "🇼🇸",
    "unicode": "U+1F1FC U+1F1F8",
    "placeholder": "",
    "dialCode": "+685",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/WS.svg",
  },
  {
    "name": "San Marino",
    "code": "SM",
    "flag": "🇸🇲",
    "unicode": "U+1F1F8 U+1F1F2",
    "placeholder": "",
    "dialCode": "+378",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SM.svg",
  },
  {
    "name": "Sao Tome & Principe",
    "code": "ST",
    "flag": "🇸🇹",
    "unicode": "U+1F1F8 U+1F1F9",
    "placeholder": "",
    "dialCode": "+239",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ST.svg",
  },
  {
    "name": "Saudi Arabia",
    "code": "SA",
    "flag": "🇸🇦",
    "unicode": "U+1F1F8 U+1F1E6",
    "placeholder": "",
    "dialCode": "+966",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SA.svg",
  },
  {
    "name": "Senegal",
    "code": "SN",
    "flag": "🇸🇳",
    "unicode": "U+1F1F8 U+1F1F3",
    "placeholder": "",
    "dialCode": "+221",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SN.svg",
  },
  {
    "name": "Serbia",
    "code": "RS",
    "flag": "🇷🇸",
    "unicode": "U+1F1F7 U+1F1F8",
    "placeholder": "",
    "dialCode": "+381",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RS.svg",
  },
  {
    "name": "Seychelles",
    "code": "SC",
    "flag": "🇸🇨",
    "unicode": "U+1F1F8 U+1F1E8",
    "placeholder": "",
    "dialCode": "+248",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SC.svg",
  },
  {
    "name": "Sierra Leone",
    "code": "SL",
    "flag": "🇸🇱",
    "unicode": "U+1F1F8 U+1F1F1",
    "placeholder": "",
    "dialCode": "+232",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SL.svg",
  },
  {
    "name": "Singapore",
    "code": "SG",
    "flag": "🇸🇬",
    "unicode": "U+1F1F8 U+1F1EC",
    "placeholder": "",
    "dialCode": "+65",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SG.svg",
  },
  {
    "name": "Sint Maarten",
    "code": "SX",
    "flag": "🇸🇽",
    "unicode": "U+1F1F8 U+1F1FD",
    "placeholder": "",
    "dialCode": "+1 721",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SX.svg",
  },
  {
    "name": "Slovakia",
    "code": "SK",
    "flag": "🇸🇰",
    "unicode": "U+1F1F8 U+1F1F0",
    "placeholder": "",
    "dialCode": "+421",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SK.svg",
  },
  {
    "name": "Slovenia",
    "code": "SI",
    "flag": "🇸🇮",
    "unicode": "U+1F1F8 U+1F1EE",
    "placeholder": "",
    "dialCode": "+386",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SI.svg",
  },
  {
    "name": "Solomon Islands",
    "code": "SB",
    "flag": "🇸🇧",
    "unicode": "U+1F1F8 U+1F1E7",
    "placeholder": "",
    "dialCode": "+677",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SB.svg",
  },
  {
    "name": "Somalia",
    "code": "SO",
    "flag": "🇸🇴",
    "unicode": "U+1F1F8 U+1F1F4",
    "placeholder": "",
    "dialCode": "+252",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SO.svg",
  },
  {
    "name": "South Africa",
    "code": "ZA",
    "flag": "🇿🇦",
    "unicode": "U+1F1FF U+1F1E6",
    "placeholder": "",
    "dialCode": "+27",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ZA.svg",
  },
  {
    "name": "South Korea",
    "code": "KR",
    "flag": "🇰🇷",
    "unicode": "U+1F1F0 U+1F1F7",
    "placeholder": "",
    "dialCode": "+82",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KR.svg",
  },
  {
    "name": "South Sudan",
    "code": "SS",
    "flag": "🇸🇸",
    "unicode": "U+1F1F8 U+1F1F8",
    "placeholder": "",
    "dialCode": "+211",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SS.svg",
  },
  {
    "name": "Spain",
    "code": "ES",
    "flag": "🇪🇸",
    "unicode": "U+1F1EA U+1F1F8",
    "placeholder": "",
    "dialCode": "+34",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ES.svg",
  },
  {
    "name": "Sri Lanka",
    "code": "LK",
    "flag": "🇱🇰",
    "unicode": "U+1F1F1 U+1F1F0",
    "placeholder": "",
    "dialCode": "+94",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LK.svg",
  },
  {
    "name": "Sudan",
    "code": "SD",
    "flag": "🇸🇩",
    "unicode": "U+1F1F8 U+1F1E9",
    "placeholder": "",
    "dialCode": "+249",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SD.svg",
  },
  {
    "name": "Suriname",
    "code": "SR",
    "flag": "🇸🇷",
    "unicode": "U+1F1F8 U+1F1F7",
    "placeholder": "",
    "dialCode": "+597",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SR.svg",
  },
  {
    "name": "Sweden",
    "code": "SE",
    "flag": "🇸🇪",
    "unicode": "U+1F1F8 U+1F1EA",
    "placeholder": "",
    "dialCode": "+46",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SE.svg",
  },
  {
    "name": "Switzerland",
    "code": "CH",
    "flag": "🇨🇭",
    "unicode": "U+1F1E8 U+1F1ED",
    "placeholder": "",
    "dialCode": "+41",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CH.svg",
  },
  {
    "name": "Syria",
    "code": "SY",
    "flag": "🇸🇾",
    "unicode": "U+1F1F8 U+1F1FE",
    "placeholder": "",
    "dialCode": "+963",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SY.svg",
  },
  {
    "name": "Taiwan",
    "code": "TW",
    "flag": "🇹🇼",
    "unicode": "U+1F1F9 U+1F1FC",
    "placeholder": "",
    "dialCode": "+886",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TW.svg",
  },
  {
    "name": "Tajikistan",
    "code": "TJ",
    "flag": "🇹🇯",
    "unicode": "U+1F1F9 U+1F1EF",
    "placeholder": "",
    "dialCode": "+992",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TJ.svg",
  },
  {
    "name": "Tanzania",
    "code": "TZ",
    "flag": "🇹🇿",
    "unicode": "U+1F1F9 U+1F1FF",
    "placeholder": "",
    "dialCode": "+255",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TZ.svg",
  },
  {
    "name": "Thailand",
    "code": "TH",
    "flag": "🇹🇭",
    "unicode": "U+1F1F9 U+1F1ED",
    "placeholder": "",
    "dialCode": "+66",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TH.svg",
  },
  {
    "name": "Timor-Leste",
    "code": "TL",
    "flag": "🇹🇱",
    "unicode": "U+1F1F9 U+1F1F1",
    "placeholder": "",
    "dialCode": "+670",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TL.svg",
  },
  {
    "name": "Togo",
    "code": "TG",
    "flag": "🇹🇬",
    "unicode": "U+1F1F9 U+1F1EC",
    "placeholder": "",
    "dialCode": "+228",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TG.svg",
  },
  {
    "name": "Tokelau",
    "code": "TK",
    "flag": "🇹🇰",
    "unicode": "U+1F1F9 U+1F1F0",
    "placeholder": "",
    "dialCode": "+690",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TK.svg",
  },
  {
    "name": "Tonga",
    "code": "TO",
    "flag": "🇹🇴",
    "unicode": "U+1F1F9 U+1F1F4",
    "placeholder": "",
    "dialCode": "+676",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TO.svg",
  },
  {
    "name": "Trinidad & Tobago",
    "code": "TT",
    "flag": "🇹🇹",
    "unicode": "U+1F1F9 U+1F1F9",
    "placeholder": "",
    "dialCode": "+1 868",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TT.svg",
  },
  {
    "name": "Tunisia",
    "code": "TN",
    "flag": "🇹🇳",
    "unicode": "U+1F1F9 U+1F1F3",
    "placeholder": "",
    "dialCode": "+216",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TN.svg",
  },
  {
    "name": "Turkey",
    "code": "TR",
    "flag": "🇹🇷",
    "unicode": "U+1F1F9 U+1F1F7",
    "placeholder": "",
    "dialCode": "+90",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TR.svg",
  },
  {
    "name": "Turkmenistan",
    "code": "TM",
    "flag": "🇹🇲",
    "unicode": "U+1F1F9 U+1F1F2",
    "placeholder": "",
    "dialCode": "+993",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TM.svg",
  },
  {
    "name": "Turks & Caicos Islands",
    "code": "TC",
    "flag": "🇹🇨",
    "unicode": "U+1F1F9 U+1F1E8",
    "placeholder": "",
    "dialCode": "+1 649",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TC.svg",
  },
  {
    "name": "Tuvalu",
    "code": "TV",
    "flag": "🇹🇻",
    "unicode": "U+1F1F9 U+1F1FB",
    "placeholder": "",
    "dialCode": "+688",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TV.svg",
  },
  {
    "name": "Uganda",
    "code": "UG",
    "flag": "🇺🇬",
    "unicode": "U+1F1FA U+1F1EC",
    "placeholder": "",
    "dialCode": "+256",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UG.svg",
  },
  {
    "name": "Ukraine",
    "code": "UA",
    "flag": "🇺🇦",
    "unicode": "U+1F1FA U+1F1E6",
    "placeholder": "",
    "dialCode": "+380",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UA.svg",
  },
  {
    "name": "United Arab Emirates",
    "code": "AE",
    "flag": "🇦🇪",
    "unicode": "U+1F1E6 U+1F1EA",
    "placeholder": "",
    "dialCode": "+971",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AE.svg",
  },
  {
    "name": "United Kingdom",
    "code": "GB",
    "flag": "🇬🇧",
    "unicode": "U+1F1EC U+1F1E7",
    "placeholder": "",
    "dialCode": "+44",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GB.svg",
  },
  {
    "name": "United States",
    "code": "US",
    "flag": "🇺🇸",
    "unicode": "U+1F1FA U+1F1F8",
    "placeholder": "",
    "dialCode": "+1",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/US.svg",
  },
  {
    "name": "Uruguay",
    "code": "UY",
    "flag": "🇺🇾",
    "unicode": "U+1F1FA U+1F1FE",
    "placeholder": "",
    "dialCode": "+598",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UY.svg",
  },
  {
    "name": "Uzbekistan",
    "code": "UZ",
    "flag": "🇺🇿",
    "unicode": "U+1F1FA U+1F1FF",
    "placeholder": "",
    "dialCode": "+998",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UZ.svg",
  },
  {
    "name": "Vanuatu",
    "code": "VU",
    "flag": "🇻🇺",
    "unicode": "U+1F1FB U+1F1FA",
    "placeholder": "",
    "dialCode": "+678",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VU.svg",
  },
  {
    "name": "Vatican City",
    "code": "VA",
    "flag": "🇻🇦",
    "unicode": "U+1F1FB U+1F1E6",
    "placeholder": "",
    "dialCode": "+379",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VA.svg",
  },
  {
    "name": "Venezuela",
    "code": "VE",
    "flag": "🇻🇪",
    "unicode": "U+1F1FB U+1F1EA",
    "placeholder": "",
    "dialCode": "+58",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VE.svg",
  },
  {
    "name": "Vietnam",
    "code": "VN",
    "flag": "🇻🇳",
    "unicode": "U+1F1FB U+1F1F3",
    "placeholder": "",
    "dialCode": "+84",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VN.svg",
  },
  {
    "name": "Wallis & Futuna",
    "code": "WF",
    "flag": "🇼🇫",
    "unicode": "U+1F1FC U+1F1EB",
    "placeholder": "",
    "dialCode": "+681",
    "image": "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/WF.svg",
  },
]
