spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:test}
  application:
    name: loan-tracker
  main:
      web-application-type: reactive

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs