spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: loan-tracker
  main:
      web-application-type: reactive

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
self:
  api-url: "http://52.74.229.194:8080"