version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/appui
permissions:
  - object: /home/ec2-user/appui
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ec2-user
