spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: loan-tracker-service
  main:
      web-application-type: reactive

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
auth:
  secret-key: ${SECRET_KEY}
  jwt-expiry-days: 30