spring:
  r2dbc:
    url: r2dbc:${DATABASE_URL}?ssl=false
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    pool:
      enabled: true
      initial-size: 5
      max-size: 10
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    placeholder-replacement: true
    validate-on-migrate: true
    url: jdbc:${DATABASE_URL}
    user: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: loan-tracker-service
  main:
    web-application-type: reactive

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
auth:
  firebase-secret-json: "firebase-secret.json"
  secret-key: ${SECRET_KEY}
  jwt-expiry-days: 30


logging:
  level:
    org.springframework.security: DEBUG
    org.flywaydb: DEBUG
currency:
  client:
    url: https://api.exchangerate-api.com/v4/latest
    base: USD
