spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
self:
  api-url: "http://localhost:8080"
auth:
  secret-key: "this is a secret that should be replaced with environment variable"