name: Deploying Frontend to dev

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-ui.yml'
      - 'mobile/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create environment.ts
        run: echo '${{ secrets.UI_ENVIRONMENT }}' > $GITHUB_WORKSPACE/mobile/src/environments/environment.ts

      #Build and push docker image
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Build and Push Docker Image
        run: |
          cd mobile
          docker buildx build --build-arg BUILD_CONFIG=dev --platform linux/amd64 -t zeeshan60/loan-tracker-ui-repo:latest --push .

      # 🔥 Deploy using Flask REST API instead of CodeDeploy
      - name: Deploy via Flask API
        run: |
          curl -X POST "https://loandeploy.codewithzeeshan.com/deploy" \
            -H "Authorization: Bearer ${{ secrets.FLASK_DEPLOY_DEV_TOKEN }}" \
            -H "Content-Type: application/json"
