name: Deploy UI to AWS

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-ui.yml'
      - 'mobile/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      #Build and push docker image
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Build and Push Docker Image
        run: |
          cd mobile
          docker build -t zeeshan60/loan-tracker-ui-repo:latest .
          docker push zeeshan60/loan-tracker-ui-repo:latest

      # 🔥 Deploy using Flask REST API instead of CodeDeploy
      - name: Deploy via Flask API
        run: |
          curl -X POST "http://52.74.229.194:5000/deploy" \
            -H "Authorization: Bearer ${{ secrets.FLASK_DEPLOY_TOKEN }}" \
            -H "Content-Type: application/json"
