name: Deploy to AWS

on:
  push:
    branches:
      - main
    paths:
      - 'loan-tracker-service/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev  # Define the environment here
    permissions:
      id-token: write
      contents: read
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create firebase-secret.json
        run: echo '${{ secrets.FIREBASE_SECRET }}' > loan-tracker-service/firebase-secret.json

      # Login to DockerHub
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          cd loan-tracker-service
          docker build -t zeeshan60/loan-tracker-service:latest .
          docker push zeeshan60/loan-tracker-service:latest


      - name: Check deploy directory
        run: |
          if [ ! -d "loan-tracker-service/deploy" ]; then
            echo "Deploy directory does not exist."
            exit 1
          fi
      - name: Package application
        run: |
          cd loan-tracker-service/deploy
          zip -r ../../deploy.zip .


      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::209479263325:role/github-role
          aws-region: ap-southeast-1

      - name: Upload to S3
        run: aws s3 cp deploy.zip s3://zflash-codedeploy-bucket/deploy.zip

      - name: Trigger AWS CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name loan-tracker-service \
            --deployment-group-name loan-tracker-deployment-group \
            --s3-location bucket=zflash-codedeploy-bucket,key=deploy.zip,bundleType=zip
