name: Deploy UI to AWS

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/mobile.yml'
      - 'mobile/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      #Build and push docker image
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Build and Push Docker Image
        run: |
          cd mobile
          docker build -t zeeshan60/loan-tracker-ui-repo:latest .
          docker push zeeshan60/loan-tracker-ui-repo:latest

      #Deploy using code deploy
      - name: Check deploy directory
        run: |
          if [ ! -d "mobile/deploy" ]; then
            echo "Deploy directory does not exist."
            exit 1
          fi
      - name: Package application
        run: |
          cd mobile/deploy
          zip -r deploy.zip .
      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::209479263325:role/github-role
          aws-region: ap-southeast-1
      - name: Upload to S3
        run: aws s3 cp mobile/deploy/deploy.zip s3://zflash-codedeploy-bucket/deployui.zip
      - name: Trigger AWS CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name loan-tracker-service \
            --deployment-group-name loan-tracker-deployment-group \
            --s3-location bucket=zflash-codedeploy-bucket,key=deployui.zip,bundleType=zip
