name: Deploy to AWS

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-service.yml'
      - 'loan-tracker-service/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup secrets, run tests, build and push docker image
      - name: Create firebase-secret.json
        run: echo '${{ secrets.FIREBASE_SECRET }}' > $GITHUB_WORKSPACE/loan-tracker-service/firebase-secret.json

      - name: Grant execute permission for Gradlew
        run: chmod +x ./loan-tracker-service/gradlew

      - name: Run tests
        run: |
          cd loan-tracker-service
          ./gradlew test

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t zeeshan60/loan-tracker-service:latest -f loan-tracker-service/Dockerfile loan-tracker-service
          docker push zeeshan60/loan-tracker-service:latest

      # 🔥 Deploy using Flask REST API instead of CodeDeploy
      - name: Deploy via Flask API
        run: |
          curl -X POST "http://52.74.229.194/:5000/deploy" \
            -H "Authorization: Bearer ${{ secrets.FLASK_DEPLOY_TOKEN }}" \
            -H "Content-Type: application/json"
