name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
      - name: Echo Current Directory
        run: |
          echo "Current directory: $(pwd)"
#      - name: Check service directory
#        run: |
#          if [ ! -d "$(pwd)/loan-tracker-service" ]; then
#            echo "Deploy directory does not exist."
#            exit 1
#          fi

      - name: Check deploy directory
        run: |
          if [ ! -d "loan-tracker-service/deploy" ]; then
            echo "Deploy directory does not exist."
            exit 1
          fi

      - name: Package application
        run: |
          zip -r deploy.zip loan-tracker-service/deploy -x "*.git*"

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::209479263325:role/github-role
          aws-region: ap-southeast-1

      - name: Upload to S3
        run: aws s3 cp deploy.zip s3://your-codedeploy-bucket/deploy.zip

      - name: Trigger AWS CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name loan-tracker-service \
            --deployment-group-name loan-tracker-deployment-group \
            --s3-location bucket=zflash-codedeploy-bucket,key=deploy.zip,bundleType=zip
